version: '2'
networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.2.0/30
services:
  backup:
    image: indiehosters/borg
    hostname: ${HOSTNAME}
    entrypoint: "cron"
    command:
    # - "--hours=*" # use $DC_HOURS to override this
    - "--minutes=10"
    - "--seconds=0"
    - "--sync-jobs"
    - "/entrypoint.sh"
    environment:
    - BORG_MODE=CLIENT
    - BORG_FOLDER
    - BORG_PASSPHRASE
    - DC_HOURS
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/domains:/domains
    - ./ssh/:/root/.ssh/
    - ./cache:/root/.cache
    - /system/metrics-collection/textfiles:/textfiles
    networks:
    - back
